### ISSUE TITLE
alias-hq keep crashing

### ISSUE THREAD

**Issue by xcxooxl** [davestewart/alias-hq#23]
Getting these errors when I try to "update source code"

```
C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\routes\api\reviews.js
```

```
  › ../../controllers/reviewsController
  › controllers\reviewsController
 ERR C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\levenary\index.flow.js Transformation error (Unexpected token, expected ";" (1:8))
SyntaxError: Unexpected token, expected ";" (1:8)
    at Object._raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:757:17)
    at Object.raiseWithData (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:750:17)
    at Object.raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:744:17)
    at Object.unexpected (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8834:16)
    at Object.semicolon (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8816:40)
    at Object.parseExpressionStatement (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11743:10)
    at Object.parseStatementContent (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11344:19)
    at Object.parseStatement (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11210:17)
    at Object.parseBlockOrModuleBlockBody (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11785:25)
    at Object.parseBlockBody (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11771:10)
 ERR C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\tar\tar.js Transformation error (Legacy octal literals are not allowed in strict mode (108:10))
SyntaxError: Legacy octal literals are not allowed in strict mode (108:10)
    at Object._raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:757:17)
    at Object.raiseWithData (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:750:17)
    at Object.raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:744:17)
    at Object.readNumber (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8340:14)
    at Object.getTokenFromCode (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8093:14)
    at Object.getTokenFromCode (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:4680:18)
    at Object.nextToken (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:7625:12)
    at Object.next (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:7550:10)
    at Object.eat (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:7555:12)
    at Object.parseObjectProperty (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:10635:14)
 ERR C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\client\node_modules\.bin\sha.js Transformation error (Unexpected token, expected "," (2:18))
SyntaxError: Unexpected token, expected "," (2:18)
    at Object._raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:757:17)
    at Object.raiseWithData (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:750:17)
    at Object.raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:744:17)
    at Object.unexpected (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8834:16)
    at Object.expect (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8820:28)
    at Object.parseCallExpressionArguments (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:9865:14)
    at Object.parseSubscript (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:9785:31)
    at Object.parseSubscript (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:1032:24)
    at Object.parseSubscripts (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:9711:19)
    at Object.parseExprSubscripts (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:9694:17)
 ERR C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\client\node_modules\levenary\index.flow.js Transformation error (Unexpected token, expected ";" (1:8))
SyntaxError: Unexpected token, expected ";" (1:8)
    at Object._raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:757:17)
    at Object.raiseWithData (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:750:17)
    at Object.raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:744:17)
    at Object.unexpected (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8834:16)
    at Object.semicolon (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8816:40)
    at Object.parseExpressionStatement (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11743:10)
    at Object.parseStatementContent (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11344:19)
    at Object.parseStatement (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11210:17)
    at Object.parseBlockOrModuleBlockBody (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11785:25)
    at Object.parseBlockBody (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11771:10)
 ERR C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\client\node_modules\prop-types\prop-types.min.js Transformation error (targetPath.startsWith is not a function)
TypeError: targetPath.startsWith is not a function
    at toAlias (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\alias-hq\cli\modules\source\transformer\paths.js:27:18)
    at NodePath.<anonymous> (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\alias-hq\cli\modules\source\transformer\transformer.js:38:25)
    at C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\jscodeshift\src\Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\jscodeshift\src\Collection.js:74:18)
    at transform (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\alias-hq\cli\modules\source\transformer\transformer.js:34:14)
    at newTransform (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\vue-jscodeshift-adapter\src\jscodeshift-mode.js:9:14)
 ERR C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\client\node_modules\shallowequal\index.original.js Transformation error (Unexpected token, expected "(" (3:38))
SyntaxError: Unexpected token, expected "(" (3:38)
    at Object._raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:757:17)
    at Object.raiseWithData (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:750:17)
    at Object.raise (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:744:17)
    at Object.unexpected (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8834:16)
    at Object.expect (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:8820:28)
    at Object.parseFunctionParams (C:\Users\xxxxx\WebstormProjects\xxxxx-postgres\node_modules\@babel\parser\lib\index.js:11947:10)
    at Object.parseFunction (C:\Use
```

my config is

```
{
  "compilerOptions": {
    "baseUrl": "",
    "paths": {
      "Models/*": ["Database\\Models/*"],
      "controllers/*": ["controllers/*"],
      "config/*": ["config/*"],
      "middleware/*": ["middleware/*"],
      "utils/*": ["utils/*"]
    }
  }
}
```

**Comment by xcxooxl** [comment]
Could it be because I use babel so I can use import instead of require?

**Comment by davestewart** [comment]
Oh, yuk! Sorry.

Not sure. Suspect it's because the config contains `\\` in the paths:

```
Legacy octal literals are not allowed in strict mode
```

Can you change it to `Database/Models/*`  (just edit the file manually) and try again? 

Also, questions:

- did you add that path, or did the config generate it?
- what did you set for Update source code > Configure options > Folders ?

**Comment by davestewart** [comment]
What IDE are you using?

**Comment by davestewart** [comment]
I can see you're using Webstorm, so we could debug this.

We will take the following steps:

- add a new package script
- add a breakpoint to the alias hq source
- run the script
- choose the options
- check the results when the script stops on the breakpoint

I'll need you to do the following to help me:

First, add a new package script:

```json
"scripts: {
  "alias": "node alias-hq"
}
```

Next, in the project explorer, open up the node for alias, and find the paths transformer file:

```
\node_modules\alias-hq\cli\modules\source\transformer\paths.js
```

Open this file, and click in the margin on line 27 so a red dot appears:

https://github.com/davestewart/alias-hq/blob/master/cli/modules/source/transformer/paths.js#L27

Right-click on the dot...

![image](https://user-images.githubusercontent.com/132681/93372366-b7510f80-f84b-11ea-9e62-c189f0df0f71.png)

...and add this in the "condition" box:

```
!targetPath.startsWith
```

Finally, in your NPM panel in Webstorm, find your new "alias" script, right click on it, and and choose "Debug":

![image](https://user-images.githubusercontent.com/132681/93372485-dcde1900-f84b-11ea-9110-447e949bbb0c.png)

Now, choose the options to update source code, and the script should stop when that error occurs.

(We know that `startsWith()` is not a function, so just to find out *why* (might not be a string))

When you get there, take a look at the `targetPath` variable and let me know what it is / post a screenshot

**Comment by xcxooxl** [comment]
![image](https://user-images.githubusercontent.com/9483548/93382665-1bcf9700-f86b-11ea-974f-f14d19fd1236.png)
targetPath is 3

**Comment by xcxooxl** [comment]
though I needed to edit the alias-hq package.json to debug this
![image](https://user-images.githubusercontent.com/9483548/93382775-4c173580-f86b-11ea-8208-460a1df7f367.png)
changed the root directory to go back to my project and then added it in folders.

**Comment by xcxooxl** [comment]
also by mistake I ran alias-hq on a single folder and then it succeeded but
what it did was 
**import appConfig from "@config\\env";**
see the double \ I think it's because I'm on windows maybe?

**Comment by davestewart** [comment]
> targetPath is 3

Blimey. No idea why that would be so.

Do you know how to use the debugger?

Can you go back up the stack and see where this started?

> import appConfig from "@config\\env";

Sounds like it.

Let me see if I can get a VM running in the next day or so, and test things on there.

Sorry about this.

**Comment by xcxooxl** [comment]
first off this error
 ERR C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\levenary\index.flow.js Transformation error (Unexpected token, expected ";" (1:8))
SyntaxError: Unexpected token, expected ";" (1:8)
    at Object._raise (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:757:17)
    at Object.raiseWithData (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:750:17)
    at Object.raise (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:744:17)
    at Object.unexpected (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:8834:16)
    at Object.semicolon (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:8816:40)
    at Object.parseExpressionStatement (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:11743:10)
    at Object.parseStatementContent (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:11344:19)
    at Object.parseStatement (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:11210:17)
    at Object.parseBlockOrModuleBlockBody (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:11785:25)
    at Object.parseBlockBody (C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\@babel\parser\lib\index.js:11771:10)
 ERR C:\Users\xxxx\WebstormProjects\xxxx-postgres\node_modules\tar\tar.js Transformation error (Legacy octal literals are not allowed in strict mode (108:1
0))

is happening regardless of the BP condition, I mean these errors happen and are printed to console without hitting breakpoint.

about where it started.. I think alias-hq is running on node_moduels as well for some reason because (where targetPath = 3)

![image](https://user-images.githubusercontent.com/9483548/93386107-dfeb0080-f86f-11ea-80cd-b386162b3e6d.png)

also my backend and frontend are in the same directory so the "client" also has node_modules of it's own.. I need to be able to exclude that directory, regardless I believe the alias-hq also runs on the node_modules of the backend project.

**Comment by davestewart** [comment]
OK. Looks like we have a few threads here.

### Your repo and setup

Questions:

- Not sure why you need to add the "root" config... is this because it's nested?
- Is your repo public? Can I clone and test it?


### Getting this working on windows

Questions:

1. do you get the same bug with "Preview updates" ?
2. would you feel confident submitting a PR for use on windows?

Re. question 2, development is fairly straightforward:

- The repo ships with a demo folder I use in development to check things are working
- The [config is all set up](https://github.com/davestewart/alias-hq/blob/master/package.json#L58-L68) so you can just clone and run

**Comment by davestewart** [comment]
> Yes I am running alias-hq from the node_modules

OK. I wonder if this has something to do with it.

It's designed to be run from your project root, where one would run general node scripts, etc. Unfortunately, I would need to see your folder hierarchy to better understand. If you can post a screenshot of your Explorer or Webstorm project tree with the appropriate files highlighted, that might be helpful.

> Not sure what that is?

The menu option before "Update files":

```
  == Alias HQ ==

  -- Main Menu --

? What do you want to do? Update source code

  -- Source Code Menu --

? What do you want to do?: 
  - Show config 
  - Show options 
  - Configure options 
❯ - Preview updates 
  - Update files - no further confirmation! 
  - Back 
``` 

> I will try to play with a bit to see if I can understand where the bug is.

Great! Let me know if I can help.

**Comment by xcxooxl** [comment]
I'm on version 5.1.5  does it have preview updates?
![image](https://user-images.githubusercontent.com/9483548/93390623-a9fd4a80-f876-11ea-852a-82e3c4b730ae.png)

project structure 
![image](https://user-images.githubusercontent.com/9483548/93390796-f183d680-f876-11ea-952e-b7d01f4278a9.png)

**Comment by davestewart** [comment]
> I'm on version 5.1.5 does it have preview updates?

Yes, you need to be in the "Update source code menu"...

Top menu:

```
  == Alias HQ ==

  -- Main Menu --

? What do you want to do? 
  - Configure paths 
  - Setup integrations 
❯ - Update source code 
  - Help 
  - Exit 
```

Then, into the "Source Code Menu":

```
  -- Source Code Menu --

? What do you want to do?: (Use arrow keys)
  - Show config 
  - Show options 
  - Configure options 
❯ - Preview updates 
  - Update files - no further confirmation! 
  - Back 
```

I presume you CAN get here???

> project structure

Is this a PHP (or other) project with a JavaScript client folder?

Normally, I would say you should be able to run Alias from `C:\Users\xxxx\WebstormProjects\xxxx-postgres\client`.

However, judging from your config, I can't see all the folders, but going on what you've shown me, I don't understand how the folder setup relates to your physical folder setup:

```
{
  "compilerOptions": {
    "baseUrl": "",
    "paths": {
      "Models/*": ["Database\\Models/*"],   <-- OK
      "controllers/*": ["controllers/*"],   <-- this looks like it's in the above folder
      "config/*": ["config/*"],             <-- same
      "middleware/*": ["middleware/*"],     <-- same
      "utils/*": ["utils/*"]                <-- can't see this folder
    }
  }
}
```

That being said, I'm guessing right now that - unless you sort this - either:

- Alias is not a good fit for your project
- You need to fix your config

If you can decide and let me know.

**Comment by xcxooxl** [comment]
I think I get it @davestewart I think it has something to do with windows encoding for some reason, Because when I re-save the file it works.. I mean the exception doesnt  happen anymore on that file.

**Comment by davestewart** [comment]
Hang on... is this because it's a PHP project?

Is this a BOM encoding issue?

https://stackoverflow.com/questions/35114000/php-session-with-utf-8-bom-encoding

**Comment by xcxooxl** [comment]
this is not a php project, it's a nodejs-express project

**Comment by davestewart** [comment]
OK, thanks for clarifying.

I think the best bet is to leave it with you for the time being. I can check in again tomorrow to find out how you got on?

**Comment by xcxooxl** [comment]
hmm kinda stuck because for some reason, after few files I re-saved it stated doing problems in files I already "fixed"
and this is when doing preview mode.. still though it loads much more files now then before, But could it be that after you open a file it changes it's encoding, or maybe the EOF byte?

**Comment by davestewart** [comment]
We could find out in two minutes:

```
git clone https://github.com/davestewart/alias-hq.git
cd alias-hq
npm i
npm run cli
```

Choose Update source code > Preview updates

**Comment by xcxooxl** [comment]
nope, worked like a charm.

**Comment by davestewart** [comment]
So if I understand you, it works on windows, using the demo folder?

That being the case, probably best I leave you to work on your other project. Perhaps you'll think of something in the shower tomorrow and that will solve it. I would like to solve it, but this sounds like an edge case.

I would recommend removing your current config TS config and running the script from your client folder.

See how that goes, and go from there.

**Comment by xcxooxl** [comment]
function transform (fileInfo, api, options) {
  // variables
  const { path, source } = fileInfo
  const ignore = ["node_modules","client"];
  if (ignore.some(x => path.includes(x)))
    return;

Added this to the top of the transform function in transfomer.js, Solved it.
I still don't like the imports look like this
![image](https://user-images.githubusercontent.com/9483548/93394505-fea3c400-f87c-11ea-8f14-d999116ab33d.png)

but atleast it works

**Comment by davestewart** [comment]
Ah, interesting!

Ignoring folders is a TODO item:

https://github.com/davestewart/alias-hq/blob/7845427d4d2ace6371bc15a423d811f24f1a7f8e/cli/modules/source/index.js#L238-L240

I'm still a little fuzzy on how your are configuring your folders, and thus how any `ignore` settings should be set.

Can you share:

- which folder you ran the script from
- your new `jsconfig.json` file
- your `package.json` `"alias-hq"` config

And I'll go from there.

**Comment by xcxooxl** [comment]
hmm because in my client I use webpack.config.js, It has much more settings than just aliases, And I'm not sure how that would work out?

ran it now from my root, I reinstalled alias-hq and just modified the small change above to ignore node_modues + client
"alias-hq": {
    "folders": [
      "."
    ],
    "modules": [
      "Models",
      "controllers",
      "config",
      "middleware",
      "utils"
    ]
  }
thats config in package.json


{
  "compilerOptions": {
    "baseUrl": "/",
    "paths": {
      "@Models/*": ["Database/Models/*"],
      "@controllers/*": ["controllers/*"],
      "@config/*": ["config/*"],
      "@middleware/*": ["middleware/*"],
      "@utils/*": ["utils/*"]
    }
  }
}
tsconfig

**Comment by xcxooxl** [comment]
oh it doesn't work
r: Cannot find module '@middleware/errorHandler'

node doesnt understand the aliases.

**Comment by davestewart** [comment]
> node doesnt understand the aliases.

https://github.com/davestewart/alias-hq/blob/master/docs/integrations.md#node

**Comment by xcxooxl** [comment]
this only works with require()
but my I use import as I installed babel to allow me to so.. import should be supported as well :S

**Comment by davestewart** [comment]
Ah crap... of course 😞

**Comment by xcxooxl** [comment]
think it's possible to add import support? maybe a babel transformer?

**Comment by davestewart** [comment]
I think that would assume you are compiling your code, in which case Webpack, rollup, etc already support this

**Comment by xcxooxl** [comment]
added rollup
though alias is failing now.
Error: Cannot find module '@services/userService'

rollup plugins
	plugins: [
		dev && run(),
		alias({
			entries: hq.get("rollup"),
		}),
		json(),
		commonjs(),
		babel({
			babelrc: false,
			plugins: ["@babel/plugin-proposal-optional-chaining"],
		}),
	],

**Comment by davestewart** [comment]
Use the "debug integrations" menu to see how paths are configured, and if necessary replace the `alias.entries` option with the raw JSON to check that it works as expected:

https://github.com/davestewart/alias-hq/blob/master/docs/cli/integrations.md#debug-integration

**Comment by davestewart** [comment]
I'm just testing rollup now to check that my advice is sound.

Although the config that Alias outputs for Rollup appears to be correct, and the paths are found, I cannot seem to get the Rollup to bundle the files properly (it treats them as an external dependency).

This is weird, as if I debug the source code of the plugin itself, it does resolve the paths correctly.

Right now, this feels like a bug or more likely a configuration issue with Rollup, rather than a problem with Alias, so I'm going to close this ticket.

I'd suggest you look at solutions for webpack and express, and go from there:

- https://www.codementor.io/@lawwantsin/compiling-our-express-server-with-webpack-lds4xof0y

Sorry this has been such a chore!

**Comment by davestewart** [comment]
OK.. edit:

I'm a dummy - I only had the `alias` plugin set up for one of the files in the demo config. 

This is my fault - I was just copy/pasting code.

So the code is actually, bundled, and the paths do actually resolve.
