### ISSUE TITLE
cli error in windows

### ISSUE THREAD

**Issue by mediabuff** [davestewart/alias-hq#82]
C:\MyDevProjects\MyLinguistics\Sanskritist.Print\lit-bindery>"./node_modules/.bin/alias-hq"

  == Alias HQ ==

  -- Main Menu --

C:\MyDevProjects\MyLinguistics\Sanskritist.Print\lit-bindery\node_modules\alias-hq\cli\index.js:60
    .prompt({
     ^

TypeError: inquirer.prompt is not a function
    at index (C:\MyDevProjects\MyLinguistics\Sanskritist.Print\lit-bindery\node_modules\alias-hq\cli\index.js:60:6)
    at Object.<anonymous> (C:\MyDevProjects\MyLinguistics\Sanskritist.Print\lit-bindery\node_modules\alias-hq\cli\index.js:99:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)

Node.js v22.9.0

**Comment by ontoneio** [comment]
Confirming that I am encountering the same bug on WSL2 Linux Ubuntu. NodeJS is LTS version.

```bash
$ pnpm alias-hq

  == Alias HQ ==

  -- Main Menu --

/workspaces/node_modules/.pnpm/alias-hq@6.2.4_@babel+preset-env@7.25.4_@babel+core@7.25.8__encoding@0.1.13/node_modules/alias-hq/cli/index.js:60
    .prompt({
     ^

TypeError: inquirer.prompt is not a function
 at index (/workspaces/node_modules/.pnpm/alias-hq@6.2.4_@babel+preset-env@7.25.4_@babel+core@7.25.8__encoding@0.1.13/node_modules/alias-hq/cli/index.js:60:6)
    at Object.<anonymous> (/workspaces/node_modules/.pnpm/alias-hq@6.2.4_@babel+preset-env@7.25.4_@babel+core@7.25.8__encoding@0.1.13/node_modules/alias-hq/cli/index.js:99:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/workspaces/node_modules/.pnpm/alias-hq@6.2.4_@babel+preset-env@7.25.4_@babel+core@7.25.8__encoding@0.1.13/node_modules/alias-hq/bin/alias-hq:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
```

**Comment by dicolasi** [comment]
same bug here on OSX
